name: scan_statistic
channels:
  - defaults
dependencies:
  - numpy=1.*
  - pandas=0.22.*
  - pip=9.0.3=py36_0
  - python=3.6
  - matplotlib=2.*
  - seaborn=0.*
  - jupyter
  - pip:
    - twobitreader==3.1.6
    - snakemake==4.*
